#!/bin/sh


SELF_DIR=/home/%%CPANELUSERHERE%%/public_html
DATABASE=$SELF_DIR/transfer/.database


# Delete the old database and content, then recreate it, assign permissions and import the dev database copy

uapi --user=%%CPANELUSERHERE%% Mysql delete_database name=%%DATABASENAME%%
uapi --user=%%CPANELUSERHERE%% Mysql create_database name=%%DATABASENAME%%
uapi --user=%%CPANELUSERHERE%% Mysql set_privileges_on_database user=%%DATABASEUSER%% database=%%DATABASENAME%% privileges=ALL%20PRIVILEGES

mysql -u root -p%%PASSWORD%% -h localhost %%DATABASENAME%% << EOF
    USE %%DATABASENAME%%;
    SET foreign_key_checks=0;
    SOURCE $DATABASE;
EOF



echo -n "Restoring file permissions and ownership..."
runperm=$SELF_DIR/.git/hooks/permissions.py

$runperm
