#!/bin/sh
# Dev site hook
# Hook utilises method of adding files to a commit automatically
# https://stackoverflow.com/questions/3284292/can-a-git-hook-automatically-add-files-to-the-commit?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

echo
touch .commit
exit
